services:
  mongodb:
    image: mongo:7
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=transfernews_db
      - CORS_ORIGINS=https://transfernews.de,https://www.transfernews.de
    depends_on:
      - mongodb
    restart: always
    expose:
      - "8001"
    networks:
      - app-network

  frontend:
    build: ./frontend
    restart: always
    expose:
      - "80"
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
